[package]
name = "authbeam"
version = "7.0.0"
edition = "2021"
description = "Authentication manager"
authors = ["trisuaso", "swmff"]
homepage = "https://rainbeam.net"
repository = "https://github.com/swmff/rainbeam"
license = "MIT"

[features]
postgres = ["databeam/postgres"]
mysql = ["databeam/mysql"]
sqlite = ["databeam/sqlite"]
redis = ["databeam/redis"]
moka = ["databeam/moka"]
oysters = ["databeam/oysters"]
default = ["databeam/sqlite", "redis"]

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }
axum-macros = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"
axum-extra = { version = "0.10.1", features = ["cookie", "multipart"] }
regex = "1.11.1"
reqwest = { version = "0.12.18", features = ["stream"] }
hcaptcha-no-wasm = { version = "3.0.1" }
mime_guess = "2.0.5"
rainbeam-shared = { version = "1.0.1" }
databeam = { path = "../databeam", version = "2.0.0", default-features = false }
image = "0.25.6"
pathbufd = "0.1.4"
bitflags = "2.9.1"
# pathbufd = { path = "../../../pathbufd" }
reva = { version = "0.13.2", features = ["with-axum"] }
reva_axum = "0.5.1"
langbeam = { path = "../langbeam" }
totp-rs = { version = "5.7.0", features = ["qr", "gen_secret"] }

[lib]
doctest = false
